server:
  port: 8080
spring:
  application:
    name: back_end
  datasource:
    url: jdbc:mysql://localhost:3306/acstation
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      key: ab1247
      expire: 7
  data:
    redis:
      host: localhost
      port: 6379
      database: 4
      timeout: 3000